import { FormEvent, useEffect, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { restoreSession, signIn, signOut } from './api/auth'
import { ApiError } from './api/client'
import { calculateCarbon, getCarbon, type CarbonResult, type Scenario } from './api/carbon'
import { getActivities, getCropSeason, getCropSeasons } from './api/crops'
import { getFarm, getPlot, getPlotsForFarm, listFarms, usingMockData } from './api/farms'
import { getResourceMetrics } from './api/metrics'
import { getMe, type CurrentUser } from './api/me'
import { getFarmPerformance, getOrganization, getOrganizationSummary, listOrganizations, type FarmPerformance, type Organization, type OrganizationSummary } from './api/organizations'
import { getMrvCase, listMrvCases, type MrvCase } from './api/mrv'
import type { Activity, CropSeason, Farm, Plot, Role } from './types'
import { visibleNav } from './roles'

const go = (to: string) => { history.pushState({}, '', to); dispatchEvent(new PopStateEvent('popstate')) }
const show = (value: number | null | undefined, suffix = '') => value == null ? 'N/A' : `${value.toLocaleString('vi-VN')}${suffix}`
const Notice = ({ children, kind = 'info' }: { children: React.ReactNode; kind?: string }) => <p className={`notice ${kind}`}>{children}</p>
const Table = ({ children }: { children: React.ReactNode }) => <div className="table-wrap"><table>{children}</table></div>

function Login({ done }: { done: (s: Session) => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const f = new FormData(e.currentTarget)
    try { const s = await signIn(String(f.get('email')), String(f.get('password'))); if (s) { done(s); go('/dashboard') } } catch (x) { setError(x instanceof Error ? x.message : 'Không thể đăng nhập.') } finally { setBusy(false) } }
  return <main className="login"><section className="login-card"><p className="eyebrow">AgriCarbon</p><h1>Dashboard HTX</h1><p>JWT chỉ được chuyển cho FastAPI để kiểm tra RLS.</p><form onSubmit={submit}><label>Email<input name="email" type="email" required /></label><label>Mật khẩu<input name="password" type="password" required /></label>{error && <Notice kind="error">{error}</Notice>}<button disabled={busy}>{busy ? 'Đang đăng nhập…' : 'Đăng nhập'}</button></form></section></main>
}

function Shell({ children, session, viewer }: { children: React.ReactNode; session: Session | null; viewer: CurrentUser }) {
  const [open, setOpen] = useState(false); const [organizationName, setOrganizationName] = useState<string | null>(null); const role = viewer.role
  useEffect(() => { if (!viewer.organizationId) { setOrganizationName(null); return } void getOrganization(viewer.organizationId).then(x => setOrganizationName(x.name)).catch(() => setOrganizationName(null)) }, [viewer.organizationId])
  const links = [['/dashboard', 'Tổng quan'], ['/organizations', 'Tổ chức'], ['/farms', 'Nông hộ'], ['/plots/plot-demo-01', 'Thửa ruộng'], ['/crop-seasons/crop-demo-01', 'Vụ canh tác'], ['/crop-seasons/crop-demo-01/carbon', 'Carbon'], ['/mrv', 'Báo cáo MRV']].filter(([to]) => visibleNav(role).includes(to))
  return <div className="app-shell"><aside className={`sidebar ${open ? 'open' : ''}`}><a className="brand" href="/dashboard" onClick={e => { e.preventDefault(); go('/dashboard') }}>AgriCarbon<small>Nông nghiệp carbon thấp</small></a><nav>{links.map(([to, label]) => <a key={to} href={to} onClick={e => { e.preventDefault(); go(to); setOpen(false) }}>{label}</a>)}</nav><footer><span className="avatar" aria-hidden="true">{(session?.user.email ?? '?')[0]?.toUpperCase()}</span><span className="footer-info"><b>{session?.user.email ?? 'Chế độ demo'}</b><small>{role}</small>{session && <button className="link" onClick={() => void signOut().then(() => go('/login'))}>Đăng xuất</button>}</span></footer></aside><div className="page"><header><button className="menu" onClick={() => setOpen(!open)}>☰</button><span><b>{organizationName ?? 'Chưa gán tổ chức'}</b></span><em>{role}</em></header><main className="content">{usingMockData && <Notice kind="warning">MOCK DATA — NOT PRODUCTION.</Notice>}{children}</main></div></div>
}

function Dashboard() { return <><h1>Tổng quan</h1><p className="subtitle">Farm → Plot → Crop Season → Activities → Carbon</p><section className="kpis">{['Tổng số hộ', 'Tổng diện tích', 'Tổng sản lượng', 'Tổng CO₂e', 'CO₂e/kg trung bình'].map(x => <article className="card kpi" key={x}><small>{x}</small><strong>N/A</strong><span>Chờ FastAPI aggregate endpoint</span></article>)}</section><section className="card"><h2>Data lineage trước UI polish</h2><p>Không hiển thị số carbon thật khi backend trả warning/lỗi. GWP và fuel factors hiện chưa production-ready.</p></section></> }

function Farms() { const [farms, setFarms] = useState<Farm[]>([]); useEffect(() => { void listFarms().then(setFarms) }, []); return <><h1>Nông hộ</h1><Table><thead><tr><th>Mã</th><th>Tên</th><th>Địa bàn</th><th>Thửa</th><th>Diện tích</th></tr></thead><tbody>{farms.map(f => <tr key={f.id} onClick={() => go(`/farms/${f.id}`)}><td>{f.code}</td><td>{f.name}</td><td>{[f.commune, f.district, f.province].filter(Boolean).join(', ') || '—'}</td><td>{f.plotCount}</td><td>{show(f.areaHa, ' ha')}</td></tr>)}</tbody></Table></> }
function Organizations() { const [organizations, setOrganizations] = useState<Organization[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [summary, setSummary] = useState<OrganizationSummary>(); const [performance, setPerformance] = useState<FarmPerformance[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { void listOrganizations().then(items => { setOrganizations(items); setSelectedId(items[0]?.id) }).catch(x => setError(x instanceof Error ? x.message : 'Không thể tải tổ chức.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (!selectedId) return; setSummary(undefined); setPerformance([]); void Promise.all([getOrganizationSummary(selectedId), getFarmPerformance(selectedId)]).then(([nextSummary, nextPerformance]) => { setSummary(nextSummary); setPerformance(nextPerformance) }).catch(x => setError(x instanceof Error ? x.message : 'Không thể tải dữ liệu tổ chức.')) }, [selectedId])
  const insufficient = (value: number | null | undefined, suffix = '') => value == null ? 'Chưa đủ dữ liệu' : show(value, suffix)
  return <><h1>Tổ chức</h1>{error && <Notice kind="error">{error}</Notice>}{loading ? <p>Đang tải tổ chức…</p> : organizations.length === 0 ? <Notice>Chưa có tổ chức nào trong phạm vi truy cập.</Notice> : <><section className="card"><label>Tổ chức<select value={selectedId} onChange={e => setSelectedId(e.target.value)}>{organizations.map(org => <option value={org.id} key={org.id}>{org.name}</option>)}</select></label></section>{summary && <section className="kpis"><article className="card kpi"><small>Số hộ</small><strong>{summary.farmCount}</strong></article><article className="card kpi"><small>Số thửa</small><strong>{summary.plotCount}</strong></article><article className="card kpi"><small>Diện tích</small><strong>{show(summary.totalAreaHa, ' ha')}</strong></article><article className="card kpi"><small>Tổng sản lượng</small><strong>{insufficient(summary.totalYieldKg, ' kg')}</strong></article><article className="card kpi"><small>Tổng CO₂e</small><strong>{insufficient(summary.totalCo2eKg, ' kg')}</strong></article><article className="card kpi"><small>CO₂e/kg</small><strong>{insufficient(summary.co2ePerKg, ' kg')}</strong></article></section>}<h2>Hiệu quả theo nông hộ</h2><Table><thead><tr><th>Farm</th><th>Area</th><th>Yield</th><th>Water/kg</th><th>Fertilizer/kg</th><th>CO₂e/kg</th><th>Cost/kg</th><th>Trạng thái dữ liệu</th></tr></thead><tbody>{performance.map(item => <tr key={item.farmId}><td>{item.farmName}</td><td>{show(item.areaHa, ' ha')}</td><td>{insufficient(item.yieldKg, ' kg')}</td><td>{insufficient(item.waterPerKg)}</td><td>{insufficient(item.fertilizerPerKg)}</td><td>{insufficient(item.co2ePerKg, ' kg')}</td><td>{insufficient(item.costPerKg)}</td><td><span className={`badge ${item.dataStatus}`}>{item.dataStatus}</span></td></tr>)}</tbody></Table></>}</> }
function FarmPage({ id }: { id: string }) { const [farm, setFarm] = useState<Farm>(); const [plots, setPlots] = useState<Plot[]>([]); useEffect(() => { void getFarm(id).then(setFarm); void getPlotsForFarm(id).then(setPlots) }, [id]); if (!farm) return <Notice kind="error">Không tìm thấy nông hộ.</Notice>; return <><h1>{farm.name}</h1><section className="card details"><p><b>Mã hộ</b>{farm.code}</p><p><b>Địa bàn</b>{[farm.commune, farm.district, farm.province].filter(Boolean).join(', ') || '—'}</p></section><h2>Thửa ruộng</h2><Table><thead><tr><th>Mã</th><th>Tên</th><th>Diện tích</th><th>Vị trí</th></tr></thead><tbody>{plots.map(p => <tr key={p.id} onClick={() => go(`/plots/${p.id}`)}><td>{p.code}</td><td>{p.name}</td><td>{show(p.areaHa, ' ha')}</td><td>{p.location ?? '—'}</td></tr>)}</tbody></Table></> }
function PlotPage({ id }: { id: string }) { const [plot, setPlot] = useState<Plot>(); const [seasons, setSeasons] = useState<CropSeason[]>([]); useEffect(() => { void getPlot(id).then(setPlot); void getCropSeasons(id).then(setSeasons) }, [id]); if (!plot) return <Notice kind="error">Không tìm thấy thửa ruộng.</Notice>; return <><h1>{plot.name}</h1><section className="card details"><p><b>Mã thửa</b>{plot.code}</p><p><b>Diện tích</b>{show(plot.areaHa, ' ha')}</p><p><b>Vị trí</b>{plot.location ?? '—'}</p></section><h2>Vụ canh tác</h2><Table><thead><tr><th>Vụ</th><th>Giống</th><th>Trạng thái</th><th>Sản lượng</th></tr></thead><tbody>{seasons.map(s => <tr key={s.id} onClick={() => go(`/crop-seasons/${s.id}`)}><td>{s.name}</td><td>{s.variety ?? '—'}</td><td>{s.status ?? '—'}</td><td>{show(s.totalYieldKg, ' kg')}</td></tr>)}</tbody></Table></> }

function Carbon({ id }: { id: string }) { const [result, setResult] = useState<CarbonResult>(); const [scenario, setScenario] = useState<Scenario>('as_recorded'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [expandedBreakdown, setExpandedBreakdown] = useState<number | null>(null)
  const dictionary = (value: unknown): Record<string, unknown> => value != null && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; const display = (value: unknown) => value == null || value === '' ? '—' : String(value); const statusClass = (value: unknown) => value === 'VERIFIED' ? 'verified' : value === 'PENDING_VERIFICATION' ? 'pending' : 'test'
  async function call(calc: boolean) { setBusy(true); setError(''); try { setResult(calc ? await calculateCarbon(id, scenario) : await getCarbon(id, scenario)); setExpandedBreakdown(null) } catch (x) { const api = x as ApiError; setError(api?.code === 'missing_emission_factor' || api?.code === 'factor_set_not_imported' ? 'Chưa thể tính do bộ hệ số phát thải chưa hoàn chỉnh.' : x instanceof Error ? x.message : 'Không thể tải Carbon.') } finally { setBusy(false) } }
  useEffect(() => { void call(false) }, [id])
  return <><h1>Carbon</h1><section className="card"><div className="row"><h2>Kết quả theo Crop Season</h2><select value={scenario} onChange={e => setScenario(e.target.value as Scenario)}><option value="as_recorded">Theo ghi nhận</option><option value="awd">AWD</option><option value="continuous_flooding">Tưới ngập liên tục</option></select></div><p className="actions"><button disabled={busy} onClick={() => void call(false)}>Xem Carbon</button><button className="secondary" disabled={busy} onClick={() => void call(true)}>Tính CO₂e</button></p>{error && <Notice kind="warning">{error}</Notice>}{result && <><section className="kpis"><article className="kpi"><small>Tổng CO₂e</small><strong>{show(result.total_co2e_kg, ' kg')}</strong></article><article className="kpi"><small>CO₂e/kg</small><strong>{show(result.co2e_per_kg, ' kg')}</strong></article></section><p>Scenario: {result.water_regime_scenario ?? result.scenario ?? '—'} · EF: {result.ef_config_version ?? '—'} · Calculated: {result.calculated_at ?? '—'}</p>{result.warnings.map(w => <Notice key={w} kind="warning">⚠ {w}</Notice>)}<Table><thead><tr><th>Nguồn</th><th>Khí</th><th>CO₂e (kg)</th><th><span className="sr-only">Chi tiết</span></th></tr></thead><tbody>{result.breakdown.map((b, i) => <><tr key={`${b.source}-${i}`}><td>{b.source}</td><td>{b.gas ?? '—'}</td><td>{show(b.co2e_kg)}</td><td><button className="drill-toggle" aria-expanded={expandedBreakdown === i} aria-controls={`breakdown-detail-${i}`} onClick={() => setExpandedBreakdown(expandedBreakdown === i ? null : i)}>{expandedBreakdown === i ? 'Ẩn chi tiết' : 'Chi tiết'}</button></td></tr>{expandedBreakdown === i && <tr id={`breakdown-detail-${i}`} className="drill-detail" key={`${b.source}-${i}-detail`}><td colSpan={4}><section aria-label={`Chi tiết phát thải ${b.source}`}><h3>Hệ số phát thải và truy xuất</h3><dl>{Object.entries(dictionary(b.factors_used)).map(([key, value]) => <><dt key={`${key}-factor-label`}>{key}</dt><dd key={`${key}-factor-value`}>{display(value)}</dd></>)}</dl><h3>Nguồn và phiên bản</h3><dl>{Object.entries(dictionary(b.provenance)).map(([key, value]) => <><dt key={`${key}-provenance-label`}>{key}</dt><dd key={`${key}-provenance-value`}>{display(value)}</dd></>)}</dl><h3>Trạng thái tham số</h3><dl>{Object.entries(dictionary(b.parameter_status)).map(([key, value]) => <><dt key={`${key}-status-label`}>{key}</dt><dd key={`${key}-status-value`}><span className={`drill-status ${statusClass(value)}`}>{display(value)}</span></dd></>)}</dl></section></td></tr>}</>)}</tbody></Table></>}</section></> }
function Season({ id, activitiesOnly = false }: { id: string; activitiesOnly?: boolean }) { const [season, setSeason] = useState<CropSeason>(); const [activities, setActivities] = useState<Activity[]>([]); const [metrics, setMetrics] = useState<{ waterPerKg: null; fertilizerPerKg: null; costPerKg: null }>(); useEffect(() => { void getCropSeason(id).then(setSeason); void getActivities(id).then(setActivities); void getResourceMetrics(id).then(setMetrics) }, [id]); if (!season) return <Notice kind="error">Không tìm thấy vụ canh tác.</Notice>; return <><h1>{activitiesOnly ? 'Activities' : season.name}</h1>{!activitiesOnly && <><section className="card details"><p><b>Giống</b>{season.variety ?? '—'}</p><p><b>Gieo sạ</b>{season.plantingDate ?? '—'}</p><p><b>Thu hoạch</b>{season.harvestDate ?? '—'}</p><p><b>Trạng thái</b>{season.status ?? '—'}</p><p><b>Tổng sản lượng</b>{show(season.totalYieldKg, ' kg')}</p></section><section className="kpis">{[['Water/kg', metrics?.waterPerKg], ['Fertilizer/kg', metrics?.fertilizerPerKg], ['Cost/kg', metrics?.costPerKg]].map(([k, v]) => <article className="card kpi" key={String(k)}><small>{k}</small><strong>{v == null ? 'N/A' : String(v)}</strong></article>)}</section>{usingMockData && <Notice>TODO BACKEND ENDPOINT: resource metrics đang mock.</Notice>}<p className="actions"><button onClick={() => go(`/crop-seasons/${id}/carbon`)}>Xem Carbon</button><button className="secondary" onClick={() => go(`/crop-seasons/${id}/activities`)}>Xem Activities</button></p></>}<h2>Danh sách hoạt động</h2><Table><thead><tr><th>Ngày</th><th>Loại</th><th>Chi tiết</th><th>Người ghi</th><th>Nguồn</th></tr></thead><tbody>{activities.map(a => <tr key={a.id}><td>{a.occurredAt}</td><td>{a.type}</td><td>{a.detail}</td><td>{a.recorder}</td><td>{a.source}</td></tr>)}</tbody></Table></> }
function Mrv() { const [mrvCase, setMrvCase] = useState<MrvCase>(); const [loading, setLoading] = useState(!usingMockData); const [error, setError] = useState('')
  useEffect(() => { if (usingMockData) return; void listMrvCases().then(items => items[0] ? getMrvCase(items[0].caseId).then(setMrvCase) : undefined).catch(x => setError(x instanceof Error ? x.message : 'Không thể tải hồ sơ MRV.')).finally(() => setLoading(false)) }, [])
  const mockSteps = ['Chuẩn bị', 'Đăng ký', 'Thiết lập đường cơ sở', 'Đo đạc', 'Báo cáo', 'Thẩm định']
  return <><h1>MRV Report</h1><Notice kind="warning">Prototype / Demo — không phải biểu mẫu chính thức hoặc báo cáo đã được cơ quan quản lý duyệt.</Notice>{error && <Notice kind="error">{error}</Notice>}{loading ? <p>Đang tải hồ sơ MRV…</p> : !usingMockData && !mrvCase ? <Notice>Chưa có hồ sơ MRV nào.</Notice> : <>{mrvCase && <section className="card details"><p><b>{mrvCase.name}</b>{mrvCase.caseCode}</p><p><b>Trạng thái</b>{mrvCase.status}</p><p><b>Kỳ báo cáo</b>{mrvCase.periodStart} — {mrvCase.periodEnd}</p></section>}<ol className="steps">{(usingMockData ? mockSteps.map((name, index) => ({ stepNo: index + 1, name, status: 'mock', startedAt: null, completedAt: null })) : mrvCase?.steps ?? []).map(step => <li key={step.stepNo}><b>{step.stepNo}. {step.name}</b><span>{step.status}{step.startedAt ? ` · Bắt đầu: ${step.startedAt}` : ''}{step.completedAt ? ` · Hoàn thành: ${step.completedAt}` : ''}</span></li>)}</ol></>}</> }

export default function App() { const [path, setPath] = useState(location.pathname); const [session, setSession] = useState<Session | null>(null); const [viewer, setViewer] = useState<CurrentUser>({ role: 'farmer', organizationId: null }); const [ready, setReady] = useState(false)
  useEffect(() => { const update = () => setPath(location.pathname); addEventListener('popstate', update); return () => removeEventListener('popstate', update) }, [])
  useEffect(() => { void restoreSession().then(setSession).catch(() => null).finally(() => setReady(true)) }, [])
  useEffect(() => { if (!session) { setViewer({ role: 'farmer', organizationId: null }); return } void getMe().then(setViewer).catch(() => setViewer({ role: 'farmer', organizationId: null })) }, [session])
  if (!ready) return <main className="login">Đang khôi phục phiên…</main>; if (path === '/login' || (import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY && !session)) return <Login done={setSession} />
  const m = (r: RegExp) => path.match(r)?.[1]; let page: React.ReactNode = <Dashboard />
  if (path === '/organizations') page = <Organizations />; else if (path === '/farms') page = <Farms />; else if (m(/^\/farms\/([^/]+)$/)) page = <FarmPage id={m(/^\/farms\/([^/]+)$/)!} />; else if (m(/^\/plots\/([^/]+)$/)) page = <PlotPage id={m(/^\/plots\/([^/]+)$/)!} />; else if (m(/^\/crop-seasons\/([^/]+)\/carbon$/)) page = <Carbon id={m(/^\/crop-seasons\/([^/]+)\/carbon$/)!} />; else if (m(/^\/crop-seasons\/([^/]+)\/activities$/)) page = <Season id={m(/^\/crop-seasons\/([^/]+)\/activities$/)!} activitiesOnly />; else if (m(/^\/crop-seasons\/([^/]+)$/)) page = <Season id={m(/^\/crop-seasons\/([^/]+)$/)!} />; else if (path === '/mrv') page = <Mrv />
  return <Shell session={session} viewer={viewer}>{page}</Shell>
}
